trigger: none

stages:
  - stage: cibuildwheel
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    jobs:
      - job: start_linux_arm64_agent_aws
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: none
          - bash: |
              echo "buildno: $(Build.BuildId)"
              echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
            env:
              AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
            displayName: "Login Azure DevOps Extension"
          - bash:
              az devops configure --defaults
              organization=$(System.TeamFoundationCollectionUri)
              project=$(System.TeamProject) --use-git-aliases true
            displayName: "Set default Azure DevOps organization and project"
          - task: LambdaInvokeFunction@1
            displayName: "Start Agent 1"
            name: "Start_Agent1"
            inputs:
              awsCredentials: "ondemand-dev"
              regionName: "eu-west-1"
              functionName: "ondemand-pipeline"
              payload: |
                {
                  "pool": "arm64-clients",
                  "buildid": "$(Build.BuildId)"
                }
              outputVariable: "functionResult"
          - bash: |
              echo "Instance: $(functionResult)"
            name: "Display_Instance"
            displayName: "Display Instance"
          - bash: |
              echo "Starting agent... for pool arm64-clients"
              POOLID=$(az pipelines pool list | jq '.[]| select(.name == "arm64-clients") | .id' -r)
              while [ "$(az pipelines agent list --pool-id $POOLID | jq '.[]| select(.name == "arm64-clients-$(Build.BuildId)") | .enabled' -r)" != "true" ]
              do
                echo "Still waiting for agent arm64-clients-$(Build.BuildId) ... "
                sleep 3
              done
              echo "Agent found ..."
            name: "Check_agent"
            displayName: "Check agent"
            timeoutInMinutes: 20
      - job: windows_x86_64
        pool: {vmImage: 'windows-2019'}
        timeoutInMinutes: 90
        steps:
          - task: UsePythonVersion@0
          - bash: |
              set -o errexit
              python3 -m pip install --upgrade pip
              python3 -m pip install cibuildwheel
            displayName: Install dependencies
          - powershell: |
              $vsPath = Resolve-Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\*\VC\Auxiliary\Build\vcvars64.bat"
              cmd /c "call `"$vsPath`" && set > env_vars.txt"
              
              Get-Content env_vars.txt | ForEach-Object {
                if ($_ -match "^(.*?)=(.*)$") {
                  [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2], "Process")
                  Write-Host "##vso[task.setvariable variable=$($matches[1])]$($matches[2])"
                }
              }
              
              # 验证环境
              cl.exe /Bv
              where.exe cl.exe
              cibuildwheel --output-dir wheelhouse .
            displayName: Build wheels
            env:
              CIBW_BUILD: "*win_amd64*"
              CIBW_ENVIRONMENT: "MSSdk=1 DISTUTILS_USE_SDK=1 SETUP_DO_GIT_SUBMODULE_INIT=1"
              CIBW_BUILD_VERBOSITY: "3"
              DISTUTILS_DEBUG: "1"
          - task: PublishBuildArtifacts@1
            inputs: {pathtoPublish: 'wheelhouse'}
