trigger: none

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              pandasVersion: ""
            linux-old-pandas:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              pandasVersion: "2.1.4"
            linux-qdb-master:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              vsQuestDbMaster: true
              pandasVersion: ""
            mac:
              imageName: "macos-latest"
              poolName: "Azure Pipelines"
              pandasVersion: ""
            windows-msvc-2019:
              imageName: "windows-2019"
              poolName: "Azure Pipelines"
              pandasVersion: ""
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 45
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - task: UsePythonVersion@0
          - script: |
              python3 --version
              python3 -m pip install cython
              python3 ci/pip_install_deps.py pandasVersion==${{ variables.pandasVersion }}
          - script: python3 proj.py build
            displayName: "Build"
          - script: |
              git clone --depth 1 https://github.com/questdb/questdb.git
            displayName: git clone questdb
            condition: eq(variables.vsQuestDbMaster, true)
          - task: Maven@3
            displayName: "Compile QuestDB"
            inputs:
              mavenPOMFile: 'questdb/pom.xml'
              jdkVersionOption: '1.11'
              options: "-DskipTests -Pbuild-web-console"
            condition: eq(variables.vsQuestDbMaster, true)
          - script: python3 proj.py test 1
            displayName: "Test vs released"
            env:
              JAVA_HOME: $(JAVA_HOME_11_X64)
          - script: python3 proj.py test 1
            displayName: "Test vs master"
            env:
              JAVA_HOME: $(JAVA_HOME_11_X64)
              QDB_REPO_PATH: './questdb'
            condition: eq(variables.vsQuestDbMaster, true)
