trigger: none

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
            linux-old-pandas:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              pandasVersion: "2.1.4"
            linux-qdb-master:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              vsQuestDbMaster: true
            mac:
              imageName: "macos-latest"
              poolName: "Azure Pipelines"
            windows-msvc-2019:
              imageName: "windows-2019"
              poolName: "Azure Pipelines"
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 90
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.12"
          - script: |
              python3 --version
              python3 -m pip install cython
            displayName: "Install cython"
          - script: python3 ci/pip_install_deps.py
            displayName: "Install pandas latest"
            condition: eq(variables.pandasVersion, '')
          - script: python3 ci/pip_install_deps.py --pandas-version==$(pandasVersion)
            displayName: "Install pandas older"
            condition: ne(variables.pandasVersion, '')
          - script: python3 proj.py build
            displayName: "Build"
          - script: |
              git clone --depth 1 https://github.com/questdb/questdb.git
            displayName: git clone questdb master
            condition: eq(variables.vsQuestDbMaster, true)
          - task: Maven@3
            displayName: "Compile QuestDB master"
            inputs:
              mavenPOMFile: "questdb/pom.xml"
              jdkVersionOption: "1.17"
              options: "-DskipTests -Pbuild-web-console"
            condition: eq(variables.vsQuestDbMaster, true)
          - script: python3 proj.py test 1
            displayName: "Test vs released"
            env:
              JAVA_HOME: $(JAVA_HOME_17_X64)
          - script: python3 proj.py test 1
            displayName: "Test vs master"
            env:
              JAVA_HOME: $(JAVA_HOME_17_X64)
              QDB_REPO_PATH: "./questdb"
            condition: eq(variables.vsQuestDbMaster, true)
      - job: TestsAgainstVariousNumpyVersion1x
        pool:
          name: "Azure Pipelines"
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 90
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.10"
          - script: |
              python3 --version
              python3 -m pip install uv
              sudo apt-get install -y libopenblas-dev pkg-config
            displayName: "Install uv"
          - script: uv run --python python --with 'numpy==1.21.0' test/test.py -v TestBufferProtocolVersionV2
            displayName: "Test vs numpy 1.21"
          - script: uv run --python python --with 'numpy==1.24.0' test/test.py -v TestBufferProtocolVersionV2
            displayName: "Test vs numpy 1.24"
          - script: uv run --python python --with 'numpy==1.26.0' test/test.py -v TestBufferProtocolVersionV2
            displayName: "Test vs numpy 1.26"
      - job: TestsAgainstVariousNumpyVersion2x
        pool:
          name: "Azure Pipelines"
          vmImage: "ubuntu-latest"
        timeoutInMinutes: 90
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.11"
          - script: |
              python3 --version
              python3 -m pip install uv
              sudo apt-get install -y libopenblas-dev pkg-config
            displayName: "Install uv"
          - script: uv run --python python run --with 'numpy==2.0.0' test/test.py -v TestBufferProtocolVersionV2
            displayName: "Test vs numpy 2.0"
          - script: uv run --python python --with 'numpy==2.2.0' test/test.py -v TestBufferProtocolVersionV2
            displayName: "Test vs numpy 2.2"
          - script: uv run --python python --with 'numpy==2.3.0' test/test.py -v TestBufferProtocolVersionV2
            displayName: "Test vs numpy 2.3"
